apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: livestream-chat
  name: livestream-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: livestream-chat
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: livestream-chat
    spec:
      containers:
        - env:
            - name: CHAT_HOST
              value: http://localhost:3001
            - name: CHAT_TITLE
              value: some dumb chat title
            - name: LOBBY_TITLE
              value: some dumb landing title
            - name: POSTER_IMAGES
              value: https://SomeImageHost.com/image1.png;https://SomeImageHost.com/image2.png;
            - name: STREAM_HOST
              value: http://localhost:8080
          image: livestream-chat
          name: livestream-chat
          ports:
            - containerPort: 3001
              protocol: TCP
      restartPolicy: Always
