apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: rtmp
  name: rtmp
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "1935"
      port: 1935
      targetPort: 1935
  selector:
    io.kompose.service: rtmp
